#!/usr/bin/perl -w
#
# l10n-closebugs -- Query debian BTS if bugs marked as open are closed.
#
# Copyright (C) 2003-2004 Tim Dijkstra
# Copyright (C) 2004 Guillem Jover
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# FUNCTION:
#  This program will query the debian BTS for records which are marked is open
#  in our db to check if they are closed. It will also correct the date of
#  an open bug to match it what the BTS says.
#

use strict;
use DBI;
use Net::LDAP;
use Date::Parse;
use Date::Format;

my $bts_host = "bugs.debian.org";
my $bts_port = 389;
my $bts_dn = "dc=bugs,dc=debian,dc=org";

my $db_name = "debian_l10n_ca";
my $db_user = "USER";
my $db_passwd = "PASSWD";
my $db_host = "localhost";
my $db_port = 3306;

my $verbose = 0;

# Setup LDAP

print " -> setup ldap\n" if $verbose;
my $ldap = Net::LDAP->new($bts_host,
			  'port' => "$bts_port",
			  'onerror' => 'die') or die "ldap init";
$ldap->bind("", 'version' => 3, 'noauth' => 1) or die "ldap bind";

# Setup SQL

print " -> setup sql\n" if $verbose;
my $dsn = "DBI:mysql:database=$db_name;host=$db_host;port=$db_port";
my $link = DBI->connect($dsn, $db_user, $db_passwd) or die "sql connect";

# Get all records with status BTS, In MySQL > 4.1 we could use a subquery
# to not also get all closed bugs (I think...)

print " -> query sql: prepare\n" if $verbose;
my $query = $link->prepare("\
		SELECT id,bugnr,name,translator,type,date \
		FROM translation \
		WHERE status='BTS'");
my $query2;

print " -> query sql: execute\n" if $verbose;
$query->execute();

print " -> query sql: loop\n" if $verbose;
while (my $row = $query->fetchrow_hashref()) {
  print "$row->{'bugnr'} $row->{'name'} $row->{'type'}\n" if $verbose;

  # See if there exists a record which shows this bug is closed
  # If so next BTS.

  $query2 = $link->prepare("\
		SELECT bugnr,name \
		FROM translation \
		WHERE status='DONE' \
			AND bugnr='$row->{'bugnr'}' \
			AND name='$row->{'name'}' \
			AND type='$row->{'type'}'");
  $query2->execute();
  $query2->rows and next;

  # Get BR from bts2ldap

  my $result = $ldap->search(base => "$bts_dn",
			     filter => "(debbugsID=$row->{'bugnr'})",
			     attrs => ['debbugsState', 'debbugsDate']) or
	       die "ldap search";

  my @entries = $result->entries;
  my $entry = $entries[0];
  my $bug_date = Date::Format::time2str("%Y-%m-%d %H\:%M\:%S",
					 $entry->get_value('debbugsDate'));
  my $bug_state = $entry->get_value('debbugsState');
  print " $bug_state\n" if $verbose;

  # If it doesn't match with what we have in db, change it.
  if ($bug_date !~ /^$row->{'date'}$/) {
    $link->do("UPDATE translation SET date='$bug_date' WHERE id='$row->{'id'}'");
  }

  # If bug is done, create a new record in db to show this
  if ($bug_state =~ /^done$/) {
    $link->do("INSERT INTO translation \
	       VALUES(null,NOW(),'$row->{'name'}','DONE','$row->{'type'}','$row->{'translator'}',null,'$row->{'bugnr'}')");
  }
}

print " -> finish\n" if $verbose;

$query->finish();
$query2->finish();
$link->disconnect();

